# fly.toml app configuration file generated for rph2024haunted on 2024-10-29T01:07:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rph2024haunted'
primary_region = 'atl'

[build]
  image = 'rpodcast/rph2024.haunted:latest'

[http_service]
  internal_port = 7771
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
